# Generated by Django 6.0.3 on 2026-04-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Digite seu nome')),
                ('email', models.EmailField(max_length=200, verbose_name='Digite seu email')),
                ('telefone', models.CharField(max_length=11, verbose_name='Digite seu telefone')),
            ],
        ),
        migrations.DeleteModel(
            name='nome',
        ),
    ]
