# Generated by Django 6.0.3 on 2026-04-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_perguntas_delete_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='perguntas',
        ),
    ]
