# Generated by Django 6.0.4 on 2026-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0003_delete_perguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Insira seu nome')),
                ('email', models.EmailField(max_length=250, verbose_name='Insira seu endereço de Email')),
                ('senha', models.CharField(max_length=20, verbose_name='Insira sua senha')),
            ],
        ),
    ]
